"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 4.2.10.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from cryptography.fernet import Fernet

load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oauth2_provider',
    'phonenumber_field',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_ratelimit',
    'users',
    'clients',
    'demo_client',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'DEBUG'},
        'oauth2_provider': {'handlers': ['console'], 'level': 'DEBUG'},
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'apps.core.security_middleware.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-device-fingerprint',
    'x-device-name',
]

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Add your production frontend URL(s) to the CORS_ORIGINS env var (comma-separated).
    # Example: CORS_ORIGINS=https://app.yourdomain.com,https://admin.yourdomain.com
    _extra = [o.strip() for o in os.getenv('CORS_ORIGINS', '').split(',') if o.strip()]
    CORS_ALLOWED_ORIGINS = [
        "https://sso-backend-6b1e.onrender.com",
        *_extra,
    ]
    # Flutter web dev server uses an arbitrary port; match any localhost origin.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
        
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = 'users.User'

# Database (Supabase)
import dj_database_url
DATABASES = {
    'default': dj_database_url.parse(os.getenv("DATABASE_URL"))
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# OAuth2 + OpenID Connect

def oidc_claims_provider(user, scopes, claims):
    # 'sub' is mandatory in every ID token
    claims['sub'] = str(user.id)

    scope_set = set(scopes) if scopes else set()

    if 'email' in scope_set:
        claims['email'] = user.email
        claims['email_verified'] = user.email_verified

    if 'profile' in scope_set:
        claims['given_name'] = user.first_name or ''
        claims['family_name'] = user.last_name or ''
        claims['name'] = f"{user.first_name} {user.last_name}".strip()
        claims['preferred_username'] = user.email.split('@')[0] if user.email else ''

    if 'phone' in scope_set:
        claims['phone_number'] = str(user.phone) if user.phone else None
        claims['phone_number_verified'] = False

    return claims

OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Lire les informations de l’utilisateur',
        'write': 'Modifier les informations de l’utilisateur',
        'openid': 'OpenID Connect (identité)',
        'profile': 'Accès au profil',
        'email': 'Accès à l’email',
        'phone': 'Accès au téléphone',
    },
    'OIDC_ENABLED': True,
    'OIDC_ISS_ENDPOINT': os.getenv('OIDC_ISS_ENDPOINT', 'https://sso-backend-6b1e.onrender.com'),
    'OIDC_RSA_PRIVATE_KEY': os.getenv('OIDC_RSA_PRIVATE_KEY'),  
    'CLIENT_ID_GENERATOR_CLASS': 'oauth2_provider.generators.ClientIdGenerator',
    'CLIENT_SECRET_GENERATOR_CLASS': 'oauth2_provider.generators.ClientSecretGenerator',
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 7,
    'PKCE_REQUIRED': True,
    'OIDC_CLAIM_PROVIDER': oidc_claims_provider,
}
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RATELIMIT_ENABLE = not DEBUG

# Redis (Upstash)
REDIS_URL = os.getenv('REDIS_URL')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Email Microservice
EMAIL_MICROSERVICE_API_KEY = os.getenv('EMAIL_MICROSERVICE_API_KEY')

# Encryption
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
if not ENCRYPTION_KEY and DEBUG:
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    import warnings
    warnings.warn(
        "ENCRYPTION_KEY not set — a temporary key was generated. "
        "Data encrypted now cannot be decrypted after a restart. "
        "Set ENCRYPTION_KEY in your .env file.",
        stacklevel=2,
    )

# AI Service
AI_SERVICE_URL = os.getenv('AI_SERVICE_URL', 'https://sso-ai-microservice.onrender.com')
AI_SERVICE_KEY = os.getenv('AI_SERVICE_KEY', None)

# Firebase / FCM
# Download your service account key from Firebase console → Project settings → Service accounts
# Set FIREBASE_CREDENTIALS_PATH to the absolute path of the JSON file inside the container
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH', None)

# CSRF & Security
CSRF_TRUSTED_ORIGINS = [
    "https://sso-backend-6b1e.onrender.com",
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += ["http://localhost:8000", "http://127.0.0.1:8000"]

# Secure cookies only over HTTPS (production). HTTP localhost dev must have these False
# or the browser drops the session cookie and PKCE flow breaks.
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG