"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 4.2.10.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from cryptography.fernet import Fernet

load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oauth2_provider',
    'phonenumber_field',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'users',
    'clients',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {
        'django.request': {'handlers': ['console'], 'level': 'DEBUG'},
        'oauth2_provider': {'handlers': ['console'], 'level': 'DEBUG'},
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",

]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
        
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = 'users.User'

# Database (Supabase)
import dj_database_url
DATABASES = {
    'default': dj_database_url.parse(os.getenv("DATABASE_URL"))
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# OAuth2 + OpenID Connect

def oidc_claims_provider(user, scopes, claims):
    import sys
    print(">>> OIDC claims provider called", file=sys.stderr)
    print(f"    User: {user.email} (id={user.id})", file=sys.stderr)
    print(f"    Scopes: {scopes}", file=sys.stderr)
    # forced claims
    claims['sub'] = str(user.id)
    claims['email'] = user.email
    claims['email_verified'] = True
    claims['given_name'] = user.first_name or ''
    claims['family_name'] = user.last_name or ''
    claims['name'] = f"{user.first_name} {user.last_name}".strip()
    claims['preferred_username'] = user.email.split('@')[0] if user.email else ''
    claims['phone_number'] = str(user.phone) if user.phone else None
    claims['phone_number_verified'] = False
    print(f"    Final claims: {claims}", file=sys.stderr)
    return claims

OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Lire les informations de l’utilisateur',
        'write': 'Modifier les informations de l’utilisateur',
        'openid': 'OpenID Connect (identité)',
        'profile': 'Accès au profil',
        'email': 'Accès à l’email',
        'phone': 'Accès au téléphone',
    },
    'OIDC_ENABLED': False,
    'OIDC_ISS_ENDPOINT': os.getenv('OIDC_ISS_ENDPOINT', 'https://sso-backend-6b1e.onrender.com'),
    'OIDC_RSA_PRIVATE_KEY': os.getenv('OIDC_RSA_PRIVATE_KEY'),  
    'CLIENT_ID_GENERATOR_CLASS': 'oauth2_provider.generators.ClientIdGenerator',
    'CLIENT_SECRET_GENERATOR_CLASS': 'oauth2_provider.generators.ClientSecretGenerator',
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 7,
    'PKCE_REQUIRED': True,
    'OIDC_CLAIM_PROVIDER': oidc_claims_provider,
}
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis (Upstash)
REDIS_URL = os.getenv('REDIS_URL')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Email (Brevo)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('BREVO_HOST', 'smtp-relay.brevo.com')
    EMAIL_PORT = int(os.getenv('BREVO_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('BREVO_USER')
    EMAIL_HOST_PASSWORD = os.getenv('BREVO_SMTP_KEY')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Encryption
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
if not ENCRYPTION_KEY and DEBUG:
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    print(f"⚠️ ENCRYPTION_KEY générée automatiquement: {ENCRYPTION_KEY}")

# AI Service
AI_SERVICE_URL = os.getenv('AI_SERVICE_URL', 'https://sso-ai-microservice.onrender.com')

# CSRF & Security
CSRF_TRUSTED_ORIGINS = [
    "https://sso-backend-6b1e.onrender.com",
]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True