# Generated by Django 4.2.10 on 2026-03-09 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricprofile',
            name='embedding',
        ),
        migrations.AddField(
            model_name='biometricprofile',
            name='encrypted_embedding',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biometricprofile',
            name='liveness_score_enrollment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
