# Generated by Django 4.2.10 on 2026-04-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
